image: docker:latest
services:
  - docker:18.09.7-dind
  -
cache:
  paths:
    - .m2/repository/
    - target/
    - variable

stages:
  - build
  - test

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn clean package
    - docker network create --subnet=172.12.0.0/16 container-network
    - docker run -d -p 4444:4444 --net=container-network --name=chromedebug selenium/standalone-chrome-debug:latest
    - docker run -d -p 5555:5555 --net=container-network --name=firefoxdebug selenium/standalone-firefox-debug:latest
  artifacts:
    paths:
      - results/
  only:
    - development

test:
  stage: test
  image: openjdk:8-jre-slim
  script:
    - java -cp target/testFramework-1.0-SNAPSHOT.jar:target/libs/* org.testng.TestNG -testnames "$testname" testng.xml
  artifacts:
    when: always
    paths:
      - target/
  only:
    - development
